appName: demo-python-app
replicas: 3

port: 5000
targetPort: 5000

namespace: default

image:
  name: shahgnp/demo-python-app
  tag: 1.0.5

hostName: app.rke2.localdomain
path: demo-python-app
ingressClassName: ingress-external

rollout:
  enabled: true
  notifications: 
    annotations:
      notifications.argoproj.io/subscribe.on-rollout-completed.slack: argo-notifications
      notifications.argoproj.io/subscribe.on-rollout-step-completed.slack: argo-notifications
      notifications.argoproj.io/subscribe.on-rollout-updated.slack: argo-notifications
      notifications.argoproj.io/subscribe.on-rollout-paused.slack: argo-notifications
      notifications.argoproj.io/subscribe.on-rollout-aborted.slack: argo-notifications
      notifications.argoproj.io/subscribe.on-scaling-replica-set.slack: argo-notifications
      notifications.argoproj.io/subscribe.on-analysis-run-error.slack: argo-notifications
      notifications.argoproj.io/subscribe.on-analysis-run-failed.slack: argo-notifications
      notifications.argoproj.io/subscribe.on-rollout-completed.googlechat: spaceName
      notifications.argoproj.io/subscribe.on-rollout-step-completed.googlechat: spaceName
      notifications.argoproj.io/subscribe.on-rollout-updated.googlechat: spaceName
      notifications.argoproj.io/subscribe.on-rollout-paused.googlechat: spaceName
      notifications.argoproj.io/subscribe.on-rollout-aborted.googlechat: spaceName
      notifications.argoproj.io/subscribe.on-scaling-replica-set.googlechat: spaceName
      notifications.argoproj.io/subscribe.on-analysis-run-error.googlechat: spaceName
      notifications.argoproj.io/subscribe.on-analysis-run-failed.googlechat: spaceName
