apiVersion: v1
kind: Service
metadata:
  name: {{ include "inficare.fullname" . }}
  labels:
    {{- include "inficare.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if and .Values.service.http .Values.service.http.port }}
    - port: {{ .Values.service.http.port }}
      targetPort: {{ default "http" .Values.containers.ports.http.containerPort }}
      protocol: {{ default "TCP" .Values.service.protocol }}
      name: http
    {{- end }}
    {{- if and .Values.service.https .Values.service.https.port }}
    - port: {{ .Values.service.https.port }}
      targetPort: {{ default "http" .Values.containers.ports.https.containerPort }}
      protocol: {{ default "TCP" .Values.service.protocol }}
      name: https
    {{- end }}
  selector:
    {{- include "inficare.selectorLabels" . | nindent 4 }}
