resources:
  - infra/project.yaml
  - infra/app.yaml
  # - infra/openebs.yaml
  - redis/project.yaml
  - redis/app.yaml
  - app/project.yaml
  - demo-python-app/app.yaml
  - demo-python-app/project.yaml
  - inficare/dev/namespace.yaml
  - inficare/dev/project.yaml
