apiVersion: {{ .Values.rollout.enabled | ternary "argoproj.io/v1alpha1" "apps/v1" }} 
kind: {{ .Values.rollout.enabled | ternary "Rollout" "Deployment" }}
metadata:
  name: {{ .Values.appName }}-{{ .Values.rollout.enabled | ternary "rollout" "deployment" }} 
  labels:
    app: {{ .Values.appName }}
  annotations:
    {{- if .Values.rollout.enabled }}
    {{- with .Values.rollout.notifications.annotations -}}
      {{- toYaml . | nindent 4 -}}
    {{- end }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: default
      containers:
        - name: {{ .Values.appName }}-app
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          # args:
          #   - sh
          #   - -c
          #   - '. /python-docker/secrets && env && python3 -m flask run --host=0.0.0.0'
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: "RuntimeDefault"
      securityContext:
        fsGroup: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
  strategy:
    canary:
      steps:
        - setWeight: 25 # Deploy 25% of the traffic to the new version
        - pause:
            duration: 30s # Wait for 30 seconds
        - setWeight: 50 # Deploy 50% of the traffic to the new version
        - pause:
            duration: 30s # Wait for 30 seconds
        - setWeight: 75 # Deploy 75% of the traffic to the new version
        - pause:
            duration: 30s # Wait for 30 seconds
        - setWeight: 100 # Deploy 100% of the traffic to the new version
      maxUnavailable: 0  # Allow one replica to be unavailable during the update

