apiVersion: {{ .Values.rollout.enabled | ternary "argoproj.io/v1alpha1" "apps/v1" }} 
kind: {{ .Values.rollout.enabled | ternary "Rollout" "Deployment" }}
metadata:
  name: {{ .Values.appName }}-{{ .Values.rollout.enabled | ternary "rollout" "deployment" }} 
  labels:
    app: {{ .Values.appName }}
  annotations:
    {{- if .Values.rollout.enabled }}
    {{- with .Values.rollout.notifications.annotations -}}
      {{- toYaml . | nindent 4 -}}
    {{- end }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: default
      containers:
        - name: {{ .Values.appName }}-app
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: "RuntimeDefault"
      securityContext:
        fsGroup: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
{{- if .Values.rollout.enabled }}
  strategy:
    {{- if eq .Values.rollout.strategy "canary" }}
    canary:
      maxUnavailable: 0  # Allow zero replicas to be unavailable during update
      steps:
        - setWeight: 25  # Deploy 25% of the traffic to the new version
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 75
        - pause:
            duration: 30s
        - setWeight: 100
        - pause:
            duration: 30s
    {{- else if eq .Values.rollout.strategy "blueGreen" }}
    blueGreen:
      activeService: {{ .Values.appName }}-active
      previewService: {{ .Values.appName }}-preview
      autoPromotionEnabled: false
    {{- else }}
    type: "Recreate"  # Fallback strategy if strategy name is not recognized
    {{- end }}
{{- end }}


