apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-preview
  labels:
    app: {{ .Values.appName }}
    type: preview
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.port }}"
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-active
  labels:
    app: {{ .Values.appName }}
    type: active
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.port }}"
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
